### ISSUE TITLE
genEth.Wallet.fromMnemonic is not a function

### ISSUE THREAD

**Issue by Ali-Hex** [Michal2SAB/Ethereum-Stealer#10]
TypeError: genEth.Wallet.fromMnemonic is not a function
    at generate (C:\Users\buou0\Desktop\Ethereum-Stealer-main\Windows\test\test.js:12:32)
    at Object.<anonymous> (C:\Users\buou0\Desktop\Ethereum-Stealer-main\Windows\test\test.js:27:5)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

**Comment by Elmirko** [comment]
"use strict";

process.title = "Ethereum Stealer by Michal2SAB";

const { ethers } = require('ethers');
const fs = require('fs');

const riches = fs.readFileSync('./riches.txt', 'utf8');

function generate() {
    var wallet = ethers.Wallet.createRandom(); // Create a random wallet directly
    console.log(wallet.address);
    if (riches.includes(wallet.address)) {
        console.log("");
        process.stdout.write('\x07');
        console.log("\x1b[32m%s\x1b[0m", ">> Success: " + wallet.address);
        var successString = "Wallet: " + wallet.address + "\n\nPrivate Key: " + wallet.privateKey + "\n\n12 word phrase: " + wallet.mnemonic.phrase;
        fs.writeFileSync('./Success.txt', successString, (err) => {
            if (err) throw err;
        });
        process.exit();
    }
}

while (true) {
    generate();
}
