### ISSUE TITLE
Error: Cannot find module '/generator.js'

### ISSUE THREAD

**Issue by minkmuck** [Michal2SAB/Ethereum-Stealer#9]
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)

    at internal/main/run_main_module.js:17:47 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}

Any fix?

**Comment by CamoCatX** [comment]
@minkmuck Install the modules to fix:

So that means you would do this: 'npm i ethers` on the command line.
